# .github/workflows/automated_build_with_attestation.yml
name: Automated Build with SBOM

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  LOWERCASE_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: pastebin
  IMAGE_TAG: latest

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM File
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          artifact-name: sbom.json
          output-file: ./sbom.json

      - name: Generate SBOM attestation
        uses: actions/attest-sbom@v1
        with:
          subject-name: ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build_push_image.outputs.digest }}
          sbom-path: './sbom.json'
          push-to-registry: true# .github/workflows/automated_build_with_attestation.yml
name: Automated Build with SBOM

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

env:
  LOWERCASE_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: pastebin
  IMAGE_TAG: latest

jobs:
  build-and-sbom:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate SBOM File
        uses: anchore/sbom-action@v0
        with:
          image: ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
          artifact-name: sbom.json
          output-file: ./sbom.json

      - name: Generate SBOM attestation
        uses: actions/attest-sbom@v1
        with:
          subject-name: ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build_push_image.outputs.digest }}
          sbom-path: './sbom.json'
          push-to-registry: true