name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository using the PAT token for authentication
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT_TOKEN }}

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install black
      - name: Install black
        run: |
          python -m pip install --upgrade pip
          pip install black

      # Run black to reformat the files
      - name: Run black and reformat files
        run: black .

      # Check for changes and commit if needed
      - name: Check if there are changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add .
          git diff --cached --exit-code || git commit -m "Auto-format Python code with black"

      # Push changes using the PAT token
      - name: Push changes
        if: "!startsWith(github.ref, 'refs/heads/develop')"
        run: |
          git push
