name: Dependency and License Scanning

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight

jobs:
  security-scanners:
    name: Security Scanners
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Trivy Scanner
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          severity: 'CRITICAL,HIGH'
          output: 'trivy-results.txt'

      # Snyk Scanner
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        continue-on-error: true  # Prevent workflow failure if vulnerabilities found
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --json-file-output=snyk-results.json

      # Generate Combined Report
      - name: Create Scanner Comparison
        run: |
          echo "# Security Scanner Results Comparison" > scanner-comparison.md
          echo "## Trivy Scan Results" >> scanner-comparison.md
          cat trivy-results.txt >> scanner-comparison.md
          echo "## Snyk Scan Results" >> scanner-comparison.md
          cat snyk-results.json >> scanner-comparison.md

      - name: Upload scan results
        uses: actions/upload-artifact@v3
        with:
          name: security-scan-results
          path: |
            trivy-results.txt
            snyk-results.json
            scanner-comparison.md