name: in-toto-attestation2
on: [push]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  test:
    runs-on: ubuntu-latest
    name: test intoto-run
    steps:
      - uses: actions/checkout@v2
      - uses: in-toto/github-action@v0.0.1
        name: intoto run command
        with:
          step-name: 'test'
          private-key: ${{ secrets.IN_TOTO_PRIVATE_KEY }}
          command: touch test.txt
          products: 'test.txt'
          archivist-url: ${{ secrets.ARCHIVIST_URL }}
          output-directory: ${{ runner.temp }}
      - name: show-attestation
        run: cat $RUNNER_TEMP/meta/*.link