
on: [push]
permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout
jobs:
  test:
    runs-on: ubuntu-latest
    name: test intoto-run
    steps:
      - uses: actions/checkout@v2
      - uses: testifysec/intoto-run-action@main
        name: intoto run command
        with:
          step-name: 'test'
          private-key: ${{ secrets.IN_TOTO_PRIVATE_KEY }}
          command: touch test.txt
          products: 'test.txt'
          exclude: "node_modules/"
          archivist-url: 'https://example.com/archivist'
          output-directory: '/path/to/output'
      - name: show-attestation
        run: cat $RUNNER_TEMP/meta/*.link