name: Build and Generate SBOM

on: [push, pull_request]

permissions:
  contents: read

jobs:
  build-generate-sbom:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Docker
        run: |
          sudo chmod 666 /var/run/docker.sock

      - name: Set Up in-toto Key
        run: |
          echo "${{ secrets.IN_TOTO_PRIVATE_KEY }}" > ci-builder.key
          chmod 600 ci-builder.key

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install in-toto

      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b $HOME/.local/bin
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build Docker Image
        run: docker build -t pastebin:latest .

      - name: Generate SBOM
        run: syft docker://pastebin:latest -o spdx-json > sbom.json

      - name: Generate SBOM Attestation
        run: |
          in-toto-run --step-name generate-sbom --materials sbom.json --products sbom.json --key ci-builder.key -- \
          echo "SBOM generation attestation"

      - name: Upload SBOM Artifact
        uses: actions/upload-artifact@v3
        with:
          name: sbom
          path: sbom.json

      - name: Upload SBOM Attestation
        uses: actions/upload-artifact@v3
        with:
          name: sbom-attestation
          path: generate-sbom.link
