name: Build, Sign, and Attest Container Image with SLSA Provenance

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      actions: read
      attestations: write

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Lowercase Variables
        run: |
          echo "LOWERCASE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_NAME=pastebin" >> $GITHUB_ENV

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker Image
        id: build_and_push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}:latest

      # Store the full image reference for later use
      - name: Set Image Reference
        run: |
          echo "IMAGE_REF=ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}@${{ steps.build_and_push.outputs.digest }}" >> $GITHUB_ENV

      - name: Generate and Attach SLSA Provenance Attestation
        id: attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}
          subject-digest: ${{ steps.build_and_push.outputs.digest }}
          push-to-registry: true
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Cosign
        uses: sigstore/cosign-installer@v2.2.0
        with:
          cosign-release: 'v2.2.0'

      - name: Debug Info
        run: |
          echo "Image Reference: ${{ env.IMAGE_REF }}"
          echo "Attestation Output: ${{ steps.attestation.outputs }}"

      - name: Wait and Verify Attestation
        run: |
          echo "Waiting for attestation to be available..."
          for i in {1..5}; do
            echo "Attempt $i of 5..."
            sleep 30
            echo "Verifying image reference: ${{ env.IMAGE_REF }}"
            if cosign verify-attestation \
              --type slsaprovenance \
              --certificate-identity-regexp "https://github.com/CSGY-9223-Group3/.*" \
              --certificate-oidc-issuer "https://token.actions.githubusercontent.com" \
              --public \
              ${{ env.IMAGE_REF }}; then
              echo "Attestation verified successfully!"
              break
            else
              if [ $i -eq 5 ]; then
                echo "Failed to verify attestation after 5 attempts"
                exit 1
              fi
              echo "Verification failed, retrying..."
            fi
          done

      - name: Download Attestation
        env:
          COSIGN_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          for i in {1..3}; do
            echo "Attempt $i to download attestation..."
            if cosign download attestation \
              --predicate-type slsaprovenance \
              ${{ env.IMAGE_REF }} > attestation.jsonl; then
              if [ -s attestation.jsonl ]; then
                echo "Successfully downloaded attestation"
                echo "Attestation content:"
                cat attestation.jsonl
                break
              fi
            fi
            if [ $i -eq 3 ]; then
              echo "Failed to download attestation after 3 attempts"
              exit 1
            fi
            echo "Download failed, retrying in 10 seconds..."
            sleep 10
          done

      - name: Upload Attestation Artifact
        uses: actions/upload-artifact@v3
        with:
          name: attestation
          path: attestation.jsonl