name: tests_security_checks

on: [push, pull_request]

jobs:
  test-cases:
    name: test-cases
    runs-on: ubuntu-latest

    permissions:
      contents: read

    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
  
  black_lint:
    name: black_lint
    runs-on: ubuntu-latest

    permissions:
      contents: read

    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v4
      - uses: psf/black@stable
  
  trufflehog:
    name: trufflehog
    runs-on: ubuntu-latest

    permissions:
      contents: read

    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          base: ""
          head: ${{ github.ref_name }}

  zap_scan:
    name: zap_scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      issues: write

    timeout-minutes: 15

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Application
        run: |
          nohup python pastebin.py &
          sleep 10  # Wait for the app to start

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://localhost:5000'
          cmd_options: '-a'
          fail_action: true
          issue_title: 'ZAP Scan Results'
          token: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

  dependency-security:
    name: dependency-security
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest

    permissions:
      contents: read
    timeout-minutes: 5

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        # Dependency Review action only works on pull requests
      - name: Dependency Review
        uses: actions/dependency-review-action@v4
  
  trivy:
    name: trivy
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      packages: write
    timeout-minutes: 15

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results-repo-scan.sarif'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy Repo scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results-repo-scan.sarif'
          category: trivy-repo-scan
      
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set Lowercase Variables
        run: |
          echo "LOWERCASE_OWNER=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV
          echo "IMAGE_NAME=pastebin" >> $GITHUB_ENV

      - name: Build and Push Image
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}:trivy_scan_${{ github.sha }}
        id: build_push_image

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        env:
          TRIVY_DB_REPOSITORY: "public.ecr.aws/aquasecurity/trivy-db:2"
        with:
          image-ref: 'ghcr.io/${{ env.LOWERCASE_OWNER }}/${{ env.IMAGE_NAME }}:trivy_scan_${{ github.sha }}'
          format: 'sarif'
          output: 'trivy-results-image-scan.sarif'
          exit-code: '0'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'MEDIUM,HIGH,CRITICAL'

      - name: Upload Trivy Image scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results-image-scan.sarif'
          category: trivy-image-scan

  snyk_scan:
    name: snyk_scan
    runs-on: ubuntu-latest

    permissions:
      contents: read
      security-events: write
      packages: write      

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Snyk Vulnerability Scan
        uses: snyk/actions@master
        continue-on-error: true
        with:
          args: test --json-file-output=vuln-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: Run Snyk License Compliance Scan
        uses: snyk/actions@master
        continue-on-error: true
        with:
          args: test --fail-on=license --json-file-output=license-report.json
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      # Upload Snyk Reports as Artifacts
      - name: Upload Snyk Report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: snyk-reports
          path: |
            vuln-report.json
            license-report.json