name: TruffleHog Secret Scan

on:
  push:
  pull_request:

jobs:
  trufflehog:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: TruffleHog Secret Scan
        uses: trufflesecurity/trufflehog@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}