name: ZAP Scan

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up ZAP
        run: |
          sudo apt-get update
          sudo apt-get install -y zaproxy

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.4.0
        with:
          target: 'http://localhost:5000'
          cmd_options: '-a'
  
      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: full_scan_report.html