name: zap_scan

on: [push, pull_request]

permissions:
  contents: read
  issues: write

jobs:
  build-and-scan:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v2

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Start Application
        run: |
          nohup python pastebin.py &
          sleep 10  # Wait for the app to start

      - name: ZAP Scan
        uses: zaproxy/action-full-scan@v0.11.0
        with:
          target: 'http://localhost:5000'
          cmd_options: '-a'
          fail_action: true
          issue_title: 'ZAP Scan Results'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v3
        with:
          name: zap-report
          path: full_scan_report.html
